/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import model.Main;
/**
 *
 * @author caiom
 */
public class Gui extends javax.swing.JPanel {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        
        jTP1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTP1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTP2 = new javax.swing.JTextPane();
        jBsomar = new javax.swing.JButton();
        jBsubtrair = new javax.swing.JButton();
        jBmultiplicar = new javax.swing.JButton();
        jBdividir = new javax.swing.JButton();
        jBlimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAhistorico = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Calculadora");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Número 1:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Número 2:");

        jScrollPane1.setViewportView(jTP1);

        jScrollPane2.setViewportView(jTP2);

        jBsomar.setText("Somar");
        jBsomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsomarActionPerformed(evt);
            }
        });

        jBsubtrair.setText("Subtrair");
        jBsubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsubtrairActionPerformed(evt);
            }
        });

        jBmultiplicar.setText("Multiplicar");
        jBmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmultiplicarActionPerformed(evt);
            }
        });

        jBdividir.setText("Dividir");
        jBdividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdividirActionPerformed(evt);
            }
        });

        jBlimpar.setText("Limpar");
        jBlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimparActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Resultado:");

        jTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF1ActionPerformed(evt);
            }
        });

        jTAhistorico.setColumns(20);
        jTAhistorico.setRows(5);
        jScrollPane3.setViewportView(jTAhistorico);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBsomar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBsubtrair)
                                .addGap(12, 12, 12)
                                .addComponent(jBmultiplicar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBdividir)
                                .addGap(18, 18, 18)
                                .addComponent(jBlimpar)
                                .addGap(0, 56, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsomar)
                    .addComponent(jBsubtrair)
                    .addComponent(jBmultiplicar)
                    .addComponent(jBdividir)
                    .addComponent(jBlimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBsomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsomarActionPerformed
        // TODO add your handling code here:
        if (jTP1.getText().trim().isEmpty() || jTP2.getText().trim().isEmpty()) {
            jTF1.setText("Preencha todos os campos");
            jTP1.requestFocus();
            return;
        }
        try {
    double num1 = Double.parseDouble(jTP1.getText().trim());
    double num2 = Double.parseDouble(jTP2.getText().trim());

    Main calc = new Main();
    double resultado = calc.somar(num1, num2);

    jTF1.setText("Resultado: " + resultado);

    jTP1.setText("");
    jTP2.setText("");
    
    jTAhistorico.append(num1 + " + " + num2 + " = " + resultado + "\n");

} catch (NumberFormatException e) {
    jTF1.setText("Erro: Digite apenas números válidos.");
} catch (ArithmeticException e) {
    jTF1.setText("Erro: " + e.getMessage());
}

    }//GEN-LAST:event_jBsomarActionPerformed

    private void jBsubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsubtrairActionPerformed
        // TODO add your handling code here:
        if (jTP1.getText().trim().isEmpty() || jTP2.getText().trim().isEmpty()) {
            jTF1.setText("Preencha todos os campos");
            jTP1.requestFocus();
            return;
        }
        try {
            double num1 = Double.parseDouble(jTP1.getText().trim());
            double num2 = Double.parseDouble(jTP2.getText().trim());

            Main calc = new Main();
            double resultado = calc.subtrair(num1, num2);

            jTF1.setText("Resultado: " + resultado);
            
            jTP1.setText("");
            jTP2.setText("");

            jTAhistorico.append(num1 + " - " + num2 + " = " + resultado + "\n");
            
        } catch (NumberFormatException ex) {
            jTF1.setText("Digite valores numéricos válidos");
        } catch (ArithmeticException ex) {
            jTF1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jBsubtrairActionPerformed

    private void jBmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmultiplicarActionPerformed
        // TODO add your handling code here:
         if (jTP1.getText().trim().isEmpty() || jTP2.getText().trim().isEmpty()) {
            jTF1.setText("Preencha todos os campos");
            jTP1.requestFocus();
            return;
        }

        try {
            double num1 = Double.parseDouble(jTP1.getText().trim());
            double num2 = Double.parseDouble(jTP2.getText().trim());

            Main calc = new Main();
            double resultado = calc.multiplicar(num1, num2);

            jTF1.setText("Resultado: " + resultado);
            
            jTP1.setText("");
            jTP2.setText("");

            jTAhistorico.append(num1 + " * " + num2 + " = " + resultado + "\n");
            
        } catch (NumberFormatException ex) {
            jTF1.setText("Digite valores numéricos válidos");
        } catch (ArithmeticException ex) {
            jTF1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jBmultiplicarActionPerformed

    private void jBdividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdividirActionPerformed
        // TODO add your handling code here:
        if (jTP1.getText().trim().isEmpty() || jTP2.getText().trim().isEmpty()) {
            jTF1.setText("Preencha todos os campos");
            jTP1.requestFocus();
            return;
        }

        try {
            double num1 = Double.parseDouble(jTP1.getText().trim());
            double num2 = Double.parseDouble(jTP2.getText().trim());

            Main calc = new Main();
            double resultado = calc.dividir(num1, num2);
            jTF1.setText("Resultado: " + resultado);
            
            jTP1.setText("");
            jTP2.setText("");

            jTAhistorico.append(num1 + " / " + num2 + " = " + resultado + "\n");
            
        } catch (NumberFormatException ex) {
            jTF1.setText("Digite valores numéricos válidos");
        } catch (ArithmeticException ex) {
            jTF1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jBdividirActionPerformed

    private void jBlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimparActionPerformed
        // TODO add your handling code here:
        jTP1.setText("");
        jTP2.setText("");
        jTF1.setText("");
        jTAhistorico.setText("");
        jTP1.requestFocus();
        
    }//GEN-LAST:event_jBlimparActionPerformed

    private void jTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdividir;
    private javax.swing.JButton jBlimpar;
    private javax.swing.JButton jBmultiplicar;
    private javax.swing.JButton jBsomar;
    private javax.swing.JButton jBsubtrair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAhistorico;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextPane jTP1;
    private javax.swing.JTextPane jTP2;
    // End of variables declaration//GEN-END:variables
}
